package de.ifcore.metis.client.message.jaxws;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 * 
 */
@WebFault(name = "addWebrangeFault", targetNamespace = "http://vgwort.de/1.2/MessageService/xsd")
public class AddWebrangeFault_Exception extends Exception
{
	private static final long serialVersionUID = -2890286125748296501L;

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private AddWebrangeFault faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public AddWebrangeFault_Exception(String message, AddWebrangeFault faultInfo)
	{
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public AddWebrangeFault_Exception(String message, AddWebrangeFault faultInfo, Throwable cause)
	{
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: de.ifcore.metis.jaxws.message.soap.message.AddWebrangeFault
	 */
	public AddWebrangeFault getFaultInfo()
	{
		return faultInfo;
	}

}
