package de.ifcore.metis.client.pixel.jaxws;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 * 
 */
@WebFault(name = "orderPixelFault", targetNamespace = "http://vgwort.de/1.0/PixelService/xsd")
public class OrderPixelFault_Exception extends Exception
{
	private static final long serialVersionUID = 513273571568018277L;

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private OrderPixelFault faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public OrderPixelFault_Exception(String message, OrderPixelFault faultInfo)
	{
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public OrderPixelFault_Exception(String message, OrderPixelFault faultInfo, Throwable cause)
	{
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: de.ifcore.metis.jaxws.pixel.OrderPixelFault
	 */
	public OrderPixelFault getFaultInfo()
	{
		return faultInfo;
	}

}
