
package de.schreibfabrik.vgwort.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Pixel", targetNamespace = "http://vgwort.de/1.0/PixelService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Pixel {


    /**
     * 
     * @param orderPixelRequest
     * @return
     *     returns de.schreibfabrik.vgwort.OrderPixelResponse
     * @throws OrderPixelFault_Exception
     */
    @WebMethod
    @WebResult(name = "orderPixelResponse", targetNamespace = "http://vgwort.de/1.0/PixelService/xsd", partName = "orderPixelResponse")
    public OrderPixelResponse orderPixel(
        @WebParam(name = "orderPixelRequest", targetNamespace = "http://vgwort.de/1.0/PixelService/xsd", partName = "orderPixelRequest")
        OrderPixelRequest orderPixelRequest)
        throws OrderPixelFault_Exception
    ;

    /**
     * 
     * @param pixelOverviewRequest
     * @return
     *     returns de.schreibfabrik.vgwort.PixelOverviewResponse
     * @throws PixelOverviewFault_Exception
     */
    @WebMethod
    @WebResult(name = "pixelOverviewResponse", targetNamespace = "http://vgwort.de/1.0/PixelService/xsd", partName = "pixelOverviewResponse")
    public PixelOverviewResponse pixelOverview(
        @WebParam(name = "pixelOverviewRequest", targetNamespace = "http://vgwort.de/1.0/PixelService/xsd", partName = "pixelOverviewRequest")
        PixelOverviewRequest pixelOverviewRequest)
        throws PixelOverviewFault_Exception
    ;

}
