
package de.ifcore.metis.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Message", targetNamespace = "http://vgwort.de/1.3/MessageService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Message {


    /**
     * 
     * @param newMessageRequest
     * @return
     *     returns de.ifcore.metis.jaxws.NewMessageResponse
     * @throws NewMessageFault_Exception
     */
    @WebMethod
    @WebResult(name = "newMessageResponse", targetNamespace = "http://vgwort.de/1.3/MessageService/xsd", partName = "newMessageResponse")
    public NewMessageResponse newMessage(
        @WebParam(name = "newMessageRequest", targetNamespace = "http://vgwort.de/1.3/MessageService/xsd", partName = "newMessageRequest")
        NewMessageRequest newMessageRequest)
        throws NewMessageFault_Exception
    ;

    /**
     * 
     * @param addWebrangeRequest
     * @return
     *     returns de.ifcore.metis.jaxws.AddWebrangeResponse
     * @throws AddWebrangeFault_Exception
     */
    @WebMethod
    @WebResult(name = "addWebrangeResponse", targetNamespace = "http://vgwort.de/1.3/MessageService/xsd", partName = "addWebrangeResponse")
    public AddWebrangeResponse addWebrange(
        @WebParam(name = "addWebrangeRequest", targetNamespace = "http://vgwort.de/1.3/MessageService/xsd", partName = "addWebrangeRequest")
        AddWebrangeRequest addWebrangeRequest)
        throws AddWebrangeFault_Exception
    ;

    /**
     * 
     * @param checkAuthorRequest
     * @return
     *     returns de.ifcore.metis.jaxws.CheckAuthorResponse
     * @throws CheckAuthorFault_Exception
     */
    @WebMethod
    @WebResult(name = "checkAuthorResponse", targetNamespace = "http://vgwort.de/1.3/MessageService/xsd", partName = "checkAuthorResponse")
    public CheckAuthorResponse checkAuthor(
        @WebParam(name = "checkAuthorRequest", targetNamespace = "http://vgwort.de/1.3/MessageService/xsd", partName = "checkAuthorRequest")
        CheckAuthorRequest checkAuthorRequest)
        throws CheckAuthorFault_Exception
    ;

    /**
     * 
     * @param qualityControlRequest
     * @return
     *     returns de.ifcore.metis.jaxws.QualityControlResponse
     * @throws QualityControlFault_Exception
     */
    @WebMethod
    @WebResult(name = "qualityControlResponse", targetNamespace = "http://vgwort.de/1.3/MessageService/xsd", partName = "qualityControlResponse")
    public QualityControlResponse qualityControl(
        @WebParam(name = "qualityControlRequest", targetNamespace = "http://vgwort.de/1.3/MessageService/xsd", partName = "qualityControlRequest")
        QualityControlRequest qualityControlRequest)
        throws QualityControlFault_Exception
    ;

}
