
package de.ifcore.metis.jaxws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "qualityControlFault", targetNamespace = "http://vgwort.de/1.3/MessageService/xsd")
public class QualityControlFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private QualityControlFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public QualityControlFault_Exception(String message, QualityControlFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public QualityControlFault_Exception(String message, QualityControlFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.ifcore.metis.jaxws.QualityControlFault
     */
    public QualityControlFault getFaultInfo() {
        return faultInfo;
    }

}
