package de.ifcore.metis.jaxws.pixel;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 * 
 */
@WebFault(name = "pixelOverviewFault", targetNamespace = "http://vgwort.de/1.0/PixelService/xsd")
public class PixelOverviewFault_Exception extends Exception
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 2198655060481231423L;
	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private PixelOverviewFault faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public PixelOverviewFault_Exception(String message, PixelOverviewFault faultInfo)
	{
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public PixelOverviewFault_Exception(String message, PixelOverviewFault faultInfo, Throwable cause)
	{
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: de.ifcore.metis.jaxws.pixel.PixelOverviewFault
	 */
	public PixelOverviewFault getFaultInfo()
	{
		return faultInfo;
	}

}
