//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 04:54:13 PM CEST 
//


package de.schreibfabrik.vgwort.xml.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://vgwort.de/1.0/PixelService/xsd}tomFault">
 *       &lt;sequence>
 *         &lt;element name="maxOrder" type="{http://vgwort.de/1.0/PixelService/xsd}int_0-Max"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maxOrder"
})
@XmlRootElement(name = "orderPixelFault")
public class OrderPixelFault
    extends TomFault
{

    protected int maxOrder;

    /**
     * Gets the value of the maxOrder property.
     * 
     */
    public int getMaxOrder() {
        return maxOrder;
    }

    /**
     * Sets the value of the maxOrder property.
     * 
     */
    public void setMaxOrder(int value) {
        this.maxOrder = value;
    }

}
